import env from './env';

export const config = {
  PORT: env.PORT,
  MONGODB_URI: env.MONGODB_URI,
  JWT_ACCESS_SECRET: env.JWT_ACCESS_SECRET,
  JWT_REFRESH_SECRET: env.JWT_REFRESH_SECRET,
  CLIENT_URL: env.CLIENT_URL,
  ALLOWED_EMAIL_DOMAIN: env.ALLOWED_EMAIL_DOMAIN,
  SUPABASE_URL: env.SUPABASE_URL,
  SUPABASE_KEY: env.SUPABASE_KEY,
  SMTP_HOST: env.SMTP_HOST,
  SMTP_PORT: env.SMTP_PORT,
  SMTP_USER: env.SMTP_USER,
  SMTP_PASS: env.SMTP_PASS,
  SMTP_SECURE: env.SMTP_SECURE,
};
