import env from './env';

export const config = {
  PORT: env.PORT,
  MONGODB_URI: env.MONGODB_URI,
  JWT_ACCESS_SECRET: env.JWT_ACCESS_SECRET,
  JWT_REFRESH_SECRET: env.JWT_REFRESH_SECRET,
  CLIENT_URL: env.CLIENT_URL,
  CLOUDINARY_CLOUD_NAME: env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: env.CLOUDINARY_API_SECRET,
  ALLOWED_EMAIL_DOMAIN: env.ALLOWED_EMAIL_DOMAIN,
};
